---
- debug: msg="{{current_relation}}"

- set_fact:
    disco: consul
    registry_uri: "consul://{{consul_api__address}}:{{consul_api__port}}"

- name: record backend uri
  lineinfile:
      dest={{charm_dir}}/backends.txt
      create=yes
      state=present
      line={{registry_uri}}
  notify:
     - start registrator container
