---
- debug: msg="stop"

- set_fact:
    backends: "cat {{charm_dir}}/backends.txt"

- debug: msg="{{ item }}"
  with_lines: "{{ backends }}"

- name: stop registrator containers
  docker:
    image=gliderlabs/registrator
    state=absent
    name="registrator-{{ item }}"
  with_lines: "{{ backends }}"

- name: erase backend
  lineinfile:
      dest="{{ charm_dir }}/backends.txt"
      create=yes
      state=absent
      line="{{ item }}"
  with_lines: "{{ backends }}"